---
- hosts: kdc
  become: yes
  tasks:
    - import_role:
        name: ansible_roles/collections/ansible_collections/tosit/tdp-extra/roles/ansible-kerberos-server

- hosts: kdc
  tasks:
    - name: Fetch krb5.conf to local files dir from kdc
      fetch:
        src: /etc/krb5.conf
        dest: files/
        flat: yes

- hosts: all
  become: yes
  tasks:
    - import_role:
        name: ansible_roles/collections/ansible_collections/tosit/tdp-extra/roles/ansible-kerberos-client

