---
- hosts: localhost
  become: False
  tasks:
    - name: Check ranger binary exists
      stat:
        path: files/ranger-2.0.1-TDP-0.1.0-SNAPSHOT-admin.tar.gz
      register: rg_exists
      failed_when: not rg_exists.stat.exists

- hosts: postgresql
  become: yes
  tasks:
    - name: Setup db and db user for ranger
      import_role:
        name: ansible_roles/collections/ansible_collections/tosit/tdp_extra/roles/ansible-role-postgresql
        tasks_from: deploy-ranger-db-requirements

- name: Deploy Ranger Admin and Usersync
  import_playbook: ansible_roles/collections/ansible_collections/tosit/tdp/playbooks/ranger.yml
