---
- hosts: localhost
  become: False
  tasks:
    - name: Check zookeeper binary exists
      stat:
        path: files/zookeeper-3.4.6.tar.gz
      register: zk_exists

    - name: Download zookeeper binary to files if missing
      shell: wget https://archive.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz -P files
      when: zk_exists.stat.exists == False

- hosts: zk
  become: yes
  tasks:
    - import_role:
        name: tosit.tdp.zookeeper

- hosts: zk
  tasks:
    - name: Verify zookeeper is serving requests
      shell: echo stat | nc localhost 2181
      register: zk_status
      failed_when: "'This ZooKeeper instance is not currently serving requests' in zk_status.stdout"
      changed_when: no
      tags: zk
