---
- hosts: localhost
  tasks:
    - name: Check ranger binary exists
      stat:
        path: files/ranger-2.0.1-TDP-0.1.0-SNAPSHOT-admin.tar.gz
      register: rg_exists
      failed_when: not rg_exists.stat.exists

- hosts: postgresql
  become: yes
  tasks:
    - name: Setup db and db user for ranger
      import_role: 
        name: ansible_roles/roles/ansible-role-postgresql
        tasks_from: deploy-ranger-db-requirements

- hosts: ranger_admin
  become: yes
  tasks:
    - name: Deploy ranger
      import_role: 
        name: tosit.tdp.ranger

- hosts: hdfs_nn
  become: yes
  tasks:
    - name: Deploy ranger hdfs plugin
      import_role: 
        name: tosit.tdp.hadoop
        tasks_from: ranger_hdfs_plugin

- hosts: yarn_rm
  become: yes
  tasks:
    - name: Deploy ranger yarn plugin
      import_role: 
        name: tosit.tdp.hadoop
        tasks_from: ranger_yarn_plugin