---
- hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: "Apply hadoop-hdfs-namenode service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: hadoop-hdfs-namenode
        enabled: "{{ hdfs_nn_start_on_boot }}"
      loop: "{{ groups['hdfs_nn'] }}"

    - name: "Apply hadoop-hdfs-journalnode service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: hadoop-hdfs-journalnode
        enabled: "{{ hdfs_jn_start_on_boot }}"
      loop: "{{ groups['hdfs_jn'] }}"

    - name: "Apply hadoop-hdfs-zkfc service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: hadoop-hdfs-zkfc
        enabled: "{{ hdfs_zkfc_start_on_boot }}"
      loop: "{{ groups['hdfs_nn'] }}"

    - name: "Apply hadoop-hdfs-datanode service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: hadoop-hdfs-datanode
        enabled: "{{ hdfs_dn_start_on_boot }}"
      loop: "{{ groups['hdfs_dn'] }}"

    - name: "Apply zookeeper service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: zookeeper
        enabled: "{{ zk_start_on_boot }}"
      loop: "{{ groups['zk'] }}"

    - name: "Apply krb5-kdc service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: krb5kdc
        enabled: "{{ krb_start_on_boot }}"
      loop: "{{ groups['kdc'] }}"

    - name: "Apply kadmin service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: kadmin
        enabled: "{{ krb_start_on_boot }}"
      loop: "{{ groups['kdc'] }}"

    - name: "Apply hbase master start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: hbase-master
        enabled: "{{ hbase_master_start_on_boot }}"
      loop: "{{ groups['hbase_master'] }}"

    - name: "Apply hbase regionserver start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: hbase-regionserver
        enabled: "{{ hbase_rs_start_on_boot }}"
      loop: "{{ groups['hbase_rs'] }}"

    - name: "Apply hadoop-yarn-resourcemanager service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: hadoop-yarn-resourcemanager
        enabled: "{{ yarn_rm_start_on_boot }}"
      loop: "{{ groups['yarn_rm'] }}"

    - name: "Apply hadoop-yarn-nodemanager service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: hadoop-yarn-nodemanager
        enabled: "{{ yarn_nm_start_on_boot }}"
      loop: "{{ groups['yarn_nm'] }}"

    - name: "Apply hadoop-yarn-timelineserver service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: hadoop-yarn-timelineserver
        enabled: "{{ yarn_ts_start_on_boot }}"
      loop: "{{ groups['yarn_ats'] }}"

    - name: "Apply hive-server2 service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: hive-server2
        enabled: "{{ hiveserver2_start_on_boot }}"
      loop: "{{ groups['hive_s2'] }}"

    - name: "Apply ranger-admin service start on boot policy"
      delegate_to: "{{ groups['ranger_admin'][0] }}"
      service:
        name: ranger-admin
        enabled: "{{ ranger_admin_start_on_boot }}"

    - name: "Apply spark-history-server service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: spark-history-server
        enabled: "{{ spark_hs_start_on_boot }}"
      loop: "{{ groups['spark_hs'] }}"

    - name: "Apply spark3-history-server service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: spark3-history-server
        enabled: "{{ spark3_hs_start_on_boot }}"
      loop: "{{ groups['spark3_hs'] }}"

    - name: "Apply knox-gateway service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: knox-gateway
        enabled: "{{ knox_start_on_boot }}"
      loop: "{{ groups['knox'] }}"

    - name: "Apply livy-server service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: livy-server-spark2
        enabled: "{{ livy_start_on_boot }}"
      loop: "{{ groups['livy_server'] }}"

    - name: "Apply livy-server-spark3 service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: livy-server-spark3
        enabled: "{{ livy_spark3_start_on_boot }}"
      loop: "{{ groups['livy_spark3_server'] }}"

    - name: "Apply zookeeper-kafka service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: zookeeper-kafka
        enabled: "{{ zk_start_on_boot }}"
      loop: "{{ groups['zk'] }}"

    - name: "Apply kafka-broker service start on boot policy"
      delegate_to: "{{ item }}"
      service:
        name: kafka-broker
        enabled: "{{ kafka_start_on_boot }}"
      loop: "{{ groups['kafka_broker'] }}"
