---
- hosts: kafka_broker
  tasks:
    - name: Upload Ranger Kafka plugin cert
      copy:
        src: "files/certs/ranger-kafka-plugin.{{ domain }}.{{ item }}"
        dest: "/etc/ssl/certs/ranger-kafka-plugin.{{ domain }}.{{ item }}"
      loop:
        - key
        - pem

- name: Deploy Kafka
  import_playbook: ansible_roles/collections/ansible_collections/tosit/tdp_extra/playbooks/meta/kafka.yml
