---
- hosts: localhost
  become: False
  tasks:
    - name: Check spark binary exists
      stat:
        path: files/spark-2.3.5-TDP-0.1.0-SNAPSHOT-bin-tdp.tgz
      register: spark_exists
      failed_when: spark_exists.stat.exists == False

- name: Deploy Spark
  import_playbook: ansible_roles/collections/ansible_collections/tosit/tdp/playbooks/meta/spark.yml

- name: Deploy Livy
  import_playbook: ansible_roles/collections/ansible_collections/tosit/tdp_extra/playbooks/meta/livy.yml
