# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.crypto
    version: 2.14.0
  - name: community.general
    version: 7.1.0
  - name: community.grafana
    version: 1.5.4
  - name: community.postgresql
    version: 2.4.2
