---
hive_user: hive
hive_jdbc_connector_package: postgresql-jdbc
hive_ms_db_url: "jdbc:postgresql://{{ groups['postgresql'][0] | tosit.tdp.access_fqdn(hostvars) }}:5432"
db_type: postgres
hive_site:
  javax.jdo.option.ConnectionURL: "{{ hive_ms_db_url }}/{{ hive_ms_db_name }}"
  javax.jdo.option.ConnectionDriverName: org.postgresql.Driver
  datanucleus.autoCreateSchema: false
  hive.zookeeper.quorum: "{{ hadoop_ha_zookeeper_quorum }}"
  javax.jdo.option.ConnectionUserName: hive
  javax.jdo.option.ConnectionPassword: hive
  hive.server2.enable.doAs: yes
  # Support hive concurrency
  hive.support.concurrency: yes
  hive.txn.manager: org.apache.hadoop.hive.ql.lockmgr.DummyTxnManager
  hive.lock.manager: org.apache.hadoop.hive.ql.lockmgr.zookeeper.ZooKeeperHiveLockManager

# Depends on hdfs service
ranger_hdfs_policies:
  - name: hive-user-hdfs-policy
    description: Hive Client Check
    isAuditEnabled: true
    isEnabled: true
    policyItems:
      - accesses:
          - { isAllowed: true, type: read }
          - { isAllowed: true, type: write }
          - { isAllowed: true, type: execute }
        conditions: []
        delegateAdmin: true
        groups: []
        users: ["{{ hive_user }}"]
    repositoryType: hdfs
    resources:
      path:
        isExcludes: false
        isRecursive: true
        values: ["hdfs:////warehouse", "hdfs:////user"]
    service: hdfs-tdp
